name: Build - Android

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - 'src/**'
  push:
    paths:
      - 'src/**'
    branches:
      - main

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 2
  MAKEFLAGS: '-j 2'

jobs:
  cancel-runs:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}

  Android:
    name: android-25
    runs-on: windows-2022
    timeout-minutes: 60
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          submodules: recursive

    - name: Setup MSBuild and add to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      id: setup_msbuild

    - name: Download Java JDK
      run: |
        $url = "https://github.com/opentibiabr/otcv8/releases/download/binary-files/jdk8u302-b08.zip"
        $outputFile = "jdk.zip"
        Invoke-WebRequest -Uri $url -OutFile $outputFile

    - name: Extract Java JDK
      run: |
        7z x jdk.zip -aoa -oC:\Android\android-sdk

    - name: Download Android NDK
      run: |
        $url = "https://github.com/opentibiabr/otcv8/releases/download/binary-files/android-ndk-r23c-windows.zip"
        $outputFile = "ndk.zip"
        Invoke-WebRequest -Uri $url -OutFile $outputFile

    - name: Extract Android NDK
      run: |
        7z x ndk.zip -aoa -oC:\Android\android-sdk

    - name: Download Apache Ant
      run: |
        $url = "https://github.com/opentibiabr/otcv8/releases/download/binary-files/apache-ant-1.9.7-bin.zip"
        $outputFile = "ant.zip"
        Invoke-WebRequest -Uri $url -OutFile $outputFile

    - name: Extract Apache Ant
      run: |
        7z x ant.zip -aoa -oC:\Android\android-sdk

    - name: Download create_android_assets script
      run: |
        $url = "https://github.com/opentibiabr/otcv8/releases/download/binary-files/create_android_assets.ps1"
        $outputFile = "create_android_assets.ps1"
        Invoke-WebRequest -Uri $url -OutFile $outputFile

    - name: Create data.zip for Android
      run: |
        powershell -ExecutionPolicy Bypass -File .\create_android_assets.ps1

    - name: Download Android Libs
      run: |
        $url = "https://github.com/opentibiabr/otcv8/releases/download/binary-files/android-libs.7z"
        $outputFile = "android_libs.7z"
        Invoke-WebRequest -Uri $url -OutFile $outputFile

    - name: Extract Android Libs
      run: |
        7z x android_libs.7z -aoa -oC:\Android

    - name: Download Android Build Tools
      run: |
        $url = "https://github.com/opentibiabr/otcv8/releases/download/binary-files/build-tools_r30-windows.zip"
        $outputFile = "build-tools.zip"
        Invoke-WebRequest -Uri $url -OutFile $outputFile

    - name: Extract Android Build Tools
      run: |
        7z x build-tools.zip -aoa -oC:\Android\android-sdk

    - name: Build for Android
      timeout-minutes: 25
      run: |
        cd android
        $env:VS_AndroidHome="C:\Android\android-sdk\build-tools_r30-windows"
        $env:VS_NdkRoot="C:\Android\android-sdk\android-ndk-r23c"
        $env:VS_AntHome="C:\Android\android-sdk\apache-ant-1.9.7"
        $env:VS_JavaHome="C:\Android\android-sdk\jdk8u302-b08"
        MSBuild.exe /p:Configuration=Release /p:Platform="ARM" /p:BUILD_REVISION=${{github.run_number}}

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: otclientv8-android-${{ github.sha }}
        path: android/otclientv8/ARM/Release/otclientv8_armv7a.apk
